import { Component, OnInit } from '@angular/core';
import { Hero } from '../../interfaces/hero.interface';
import { HeroesService } from '../../services/heroes.service';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-list-page',
  templateUrl: './list-page.component.html',
  styles: [
  ]
})
export class ListPageComponent implements OnInit {
  public heroes: Hero[] = [];

  public forecasts: WeatherForecast[]= [];
  public pizzas: Pizza[]= [];
  constructor( private heroesService: HeroesService,private http: HttpClient){}

  ngOnInit(): void {
    this.heroesService.getHeroes().subscribe( heroes =>  this.heroes = heroes );
    this.http.get<Pizza[]>('https://localhost:7213/Pizza').subscribe(
      pizzas => { this.pizzas = pizzas; console.log(pizzas);

    });
    this.getPizzas();



  }

  getPizzas(){
    return this.http.get<Pizza[]>('https://localhost:7213/Pizza').subscribe(
      pizzas => { this.pizzas = pizzas; console.log(pizzas);
      });
  }
}
// Generated by https://quicktype.io

export interface Pizza {
  id:           number;
  name:         string;
  isGlutenFree: boolean;
}

interface WeatherForecast {
  date: string;
  temperatureC: number;
  temperatureF: number;
  summary: string;
}
